language: node_js

os:
  - linux
  - osx

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - npm install
  - npm run lint
  - ./script/atom-ci-install

git:
  depth: false

branches:
  only:
    - master
