language: node_js

node_js:
  - 12

os:
  - linux
  - osx

env:
  - ATOM_CHANNEL=stable
  - ATOM_CHANNEL=nightly

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - npm install
  - npm run lint
  - ./script/atom-ci-install

git:
  depth: false

branches:
  only:
    - master
