language: objective-c

os:
  - linux
  - osx

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - npm --version
  - "curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh"

git:
  depth: false

branches:
  only:
    - master
