language: minimal

os:
  - linux
  - osx

dist: xenial
services:
  - xvfb

notifications:
  email:
    on_success: never
    on_failure: change

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 3

branches:
  only:
    - master
