#!/usr/bin/env node

const cp = require("child_process");
const path = require("path");

function isLinux() {
  return process.platform === "linux";
}

function isMac() {
  return process.platform === "darwin";
}

function isWindows() {
  return process.platform === "win32";
}

function downloadAtom(platform, channel) {
  const downloadLink = `https://atom.io/download/${platform}?channel=${channel}`;
  const header = "Accept: application/octet-stream";

  let outFile;
  if (isLinux()) {
    outFile = "atom-amd64.deb";
  } else {
    outFile = "atom.zip";
  }

  console.log(`Downloading Atom from ${downloadLink} to file ${outFile}`);
  return {
    child: cp.spawnSync("curl", ["-s", "-L", "-H", header, downloadLink, "-o", outFile]),
    out: outFile,
  };
}

function getAtomPlatform() {
  if (isLinux()) {
    return "deb";
  } else if (isMac()) {
    return "mac";
  } else if (isWindows()) {
    return "windows_zip";
  } else {
    throw new Error("Unknown platform");
  }
}

function installAtom(download) {
  console.log(download);
}

installAtom(downloadAtom(getAtomPlatform(), "stable"));

console.log("done");
