#!/usr/bin/env node

const cp = require("child_process");

function isLinux() {
  return process.platform === "linux";
}

function isMac() {
  return process.platform === "darwin";
}

function isWindows() {
  return process.platform === "win32";
}

function installAtom(platform, channel) {
  return new Promise((resolve, reject) => {
    const downloadLink = `https://atom.io/download/${platform}?channel=${channel}`;
    const header = "Accept: application/octet-stream";

    let outFile;
    if (isLinux()) {
      outFile = "atom-amd64.deb";
    } else {
      outFile = "atom.zip";
    }

    console.log(`Downloading Atom from ${downloadLink} to file ${outFile}`);
    const download = cp.spawn("curl", ["-s", "-L", "-H", header, downloadLink, "-o", outFile]);

    download.on("exit", (code) => {
      if (code) {
        console.log(`Rejected: ${code}`);
        reject(code);
      } else {
        console.log(`Downloaded: ${code}`)
        resolve(code);
      }
    });
  });
}

function getAtomPlatform() {
  if (isLinux()) {
    return "deb";
  } else if (isMac()) {
    return "mac";
  } else if (isWindows()) {
    return "windows_zip";
  } else {
    throw new Error("Unknown platform");
  }
}


installAtom(getAtomPlatform(), "stable").then(() => { console.log("done"); });
