name: Lint

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  lint:
    if: "!contains(github.event.head_commit.message, '!skip')"
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Install
        run: npm install prettier --no-save
      - name: Lint
        run: npm run lint-write
      - name: Commit Fixes
        if: "!github.event.release"
        uses: EndBug/add-and-commit@a988073222b8bd50f3ecfca9c0ab7dfbf0d08ceb
        with:
          author_name: snippets-plus-lint-bot
          message: "Fix lint issues"
