name: Tests

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*
  release:
    types:
      - created
  schedule:
    - cron: "0 2 * * 6"
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '!skip')"
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
        channel: [stable, nightly]

    name: "Test (${{ matrix.channel }}) - ${{ matrix.os }} "

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Install
        run: npm install
      - name: Test
        env:
          ATOM_CHANNEL: ${{ matrix.channel }}
          TRAVIS_OS_NAME: 
        run: ./script/atom-ci-install
